"""Add last_store_notification column

Revision ID: 127cbbaa687d
Revises: b2fc0eabb8d8
Create Date: 2026-07-05 23:49:03.616768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '127cbbaa687d'
down_revision: Union[str, Sequence[str], None] = 'b2fc0eabb8d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_settings', sa.Column('last_store_notification', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_settings', 'last_store_notification')
    # ### end Alembic commands ###
