"""Fix database state

Revision ID: 2013c1a48e1c
Revises: 48e90c8cf584
Create Date: 2026-07-06 15:37:15.992336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2013c1a48e1c'
down_revision: Union[str, Sequence[str], None] = '48e90c8cf584'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_settings',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('last_list_message_id', sa.Integer(), nullable=True),
    sa.Column('last_store_notification', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('chat_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_settings')
    # ### end Alembic commands ###
