"""Add user_name to shopping_list

Revision ID: 48e90c8cf584
Revises: 127cbbaa687d
Create Date: 2026-07-06 15:32:48.028603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48e90c8cf584'
down_revision: Union[str, Sequence[str], None] = '127cbbaa687d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_settings')
    op.add_column('shopping_list', sa.Column('user_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shopping_list', 'user_name')
    op.create_table('chat_settings',
    sa.Column('chat_id', sa.BIGINT(), nullable=False),
    sa.Column('last_list_message_id', sa.INTEGER(), nullable=True),
    sa.Column('last_store_notification', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('chat_id')
    )
    # ### end Alembic commands ###
