"""Add amount column

Revision ID: 544d6e69ce0c
Revises: 5ed732016dd6
Create Date: 2026-07-05 23:04:54.700250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '544d6e69ce0c'
down_revision: Union[str, Sequence[str], None] = '5ed732016dd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_list', sa.Column('amount', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shopping_list', 'amount')
    # ### end Alembic commands ###
