"""Add chat settings table

Revision ID: b2fc0eabb8d8
Revises: 544d6e69ce0c
Create Date: 2026-07-05 23:12:04.428606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2fc0eabb8d8'
down_revision: Union[str, Sequence[str], None] = '544d6e69ce0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_settings',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('last_list_message_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('chat_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_settings')
    # ### end Alembic commands ###
